app/models/wpcc/contributions_calendar.rb, app/models/wpcc/period_contribution.rb, app/models/wpcc/period_contribution_calculator.rb, config/contribution_periods.yml, lib/wpcc.rb, spec/models/contributions_calendar_spec.rb, spec/models/period_contribution_calculator_spec.rb, spec/models/period_contribution_spec.rb
TP Ticket: https://moneyadviceservice.tpondemand.com/entity/8289
This PR address **only** the ruby classes that will be responsible for calculations of your results page.
We created a class called ContributionsCalendar that will be responsible to return all the contributions calculation for the period and the user input of their employee percentage and employer percentage contribution in relation to the eligible salary. You can see more example on the user stories.
An example on how to use the ContributionsCalendar class:
```ruby
Wpcc::ContributionsCalendar.new(
eligible_salary: 12_124, 
employer_percent: 1, 
employee_percent: 1, 
salary_frequency: 12
).schedule
#<Wpcc::PeriodContribution:0x007f9d5be9d9c8
#<Wpcc::PeriodContribution:0x007f9d5be9d798
```
=> [DEV APPROVED] 8289 your results calculations

app/controllers/wpcc/your_results_controller.rb, app/models/wpcc/contributions_calendar.rb, app/models/wpcc/period_contribution.rb, app/models/wpcc/period_contribution_calculator.rb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, config/routes.rb, spec/controllers/your_results_controller_spec.rb, spec/models/contributions_calendar_spec.rb, spec/models/period_contribution_calculator_spec.rb
This PR addresses tasks 8349 and 8350 of [user story TP 8289](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=f363bea37e60ac292c07aaf8b50f0da9#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8289/silent).
It adds the controller and routes that the step 2 form will post to, and a basic view for displaying the users results. PR #4 addressed the logic required to do the calculations.
=> 8289 Your results controller, route and view.

app/views/layouts/wpcc/engine.html.erb
This is the smallest of changes, but something I noticed by accident that we need to include.  The viewport element instructs the browser on how to handle scaling and dimensions, so we dont see the full width, tiny site on mobile
=> [DEV APPROVED] Adding viewport tag

app/assets/stylesheets/wpcc/base/_section.scss, app/assets/stylesheets/wpcc/base/_wpcc.scss, app/assets/stylesheets/wpcc/section/_contributions.scss, app/assets/stylesheets/wpcc/section/_details.scss, app/views/wpcc/your_details/new.html.erb
Also places section contents into containers that can be hidden for each step while still displaying the section title.
| All sections open |
|---------|
|![wpcc_expanded](https://user-images.githubusercontent.com/13165846/27825129-7dbc3564-60a6-11e7-9c79-c145599f5b9e.png)|
| All sections closed |
|-----------|
|![wpcc_collapsed](https://user-images.githubusercontent.com/13165846/27825147-86cc6336-60a6-11e7-9bea-7d7d268cb613.png)|
=> Adds section borders

app/models/wpcc/contributions_calendar.rb, app/models/wpcc/period_contribution_calculator.rb, spec/models/contributions_calendar_spec.rb, spec/models/period_contribution_calculator_spec.rb
This PR addresses https://moneyadviceservice.tpondemand.com/entity/8319
When a user inputs contributions higher than the minimum in future periods then those tables should not appear.
=> 8319 Reduce Contribution table results

Gemfile, Gemfile.lock, README.md
This PR alters Rubocop from being available to the _build_ group only. It adds it to the _development_ group too. It ensures that the version of Rubocop that runs for the build group is the same version(`~> 0.49.1`) for running Rubocop locally in development mode.
=> Adds Rubocop to 'build' and 'development' group

app/controllers/wpcc/your_contributions_controller.rb, app/controllers/wpcc/your_details_controller.rb, app/models/wpcc/your_details_form.rb, app/presenters/wpcc/your_details_form_presenter.rb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/your_details_section_steps.rb, features/support/ui/your_contributions.rb, features/support/ui/your_details.rb, features/support/world/pages.rb, features/your_details_section.feature, spec/controllers/your_contributions_controller_spec.rb, spec/controllers/your_details_controller_spec.rb, spec/models/your_details_form_spec.rb, spec/presenters/your_details_form_presenter_spec.rb
This pr addresses [TP task 8393](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=task/8393). The data input in Step 1 needs to persist as all the 'steps' in the WPCC journey use it.
* We decided to store the data in a session as there is no database requirement.
* The view is simplified. Future prs will style it.
=> 8393 Step1 create session

app/assets/stylesheets/wpcc/base/_section.scss, app/views/wpcc/your_contributions/new.html.erb
Task #8294 of [TP User Story 8284](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8284) - Adds style to the summary in the title of step 1
Adds style to the summary in the title of step 1 when the user has completed the step
Relates to PR:
https://github.com/moneyadviceservice/wpcc/pull/23
=> [DEV APPROVED] 8393 - Adds style to the summary in the title of step 1

Gemfile.lock, app/models/wpcc/minimum_contribution_calculator.rb
Wrapping 
`class MinimumContributionCalculator < ContributionCalculator`
in `module Wpcc`
threw an error on the frontend mount 
```
TypeError - superclass must be a Class (Module given):
.../wpcc/minimum_contribution_calculator.rb:4:in <module:Wpcc>
.../wpcc/minimum_contribution_calculator.rb:3:in <top (required)>
```
Thanks to @Tr4pSt3R for quickly thinking of the solution. 
`class Wpcc::MinimumContributionCalculator < Wpcc::ContributionCalculator`
=> Fix namespacing of wpcc module

app/controllers/wpcc/your_details_controller.rb, app/models/wpcc/contribution_calculator.rb, app/models/wpcc/full_contribution_calculator.rb, app/models/wpcc/minimum_contribution_calculator.rb, app/models/wpcc/your_contributions_form.rb, app/models/wpcc/your_details_form.rb
The active model require is unnecessary since we are requiring
the active model on the main file lib/wpcc.rb there is the
first file to be load when the gem is added in any project as you can see here:
https://github.com/moneyadviceservice/wpcc/blob/master/lib/wpcc.rb#L1
=> Remove active model require all over the place

Gemfile, Gemfile.lock, app/controllers/wpcc/your_contributions_controller.rb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/edit_your_contributions.feature, features/step_definitions/your_contributions_steps.rb, features/step_definitions/your_details_section_steps.rb, features/support/ui/your_contributions.rb, features/support/ui/your_results.rb, features/support/world/pages.rb, spec/controllers/your_contributions_controller_spec.rb
This PR refers to https://moneyadviceservice.tpondemand.com/entity/8287
Now it possible to be on the third step and return to the step 2.
So as the other step, the **form object should know how to render the inputs**.
Some notes that I added on this PR:
* Added the launchy gem to help when we are creating the cucumber specs. Because it is annoying to save_and_open_page and not open due to the gem not be in the project.
* Changed the button on step 2 to be an input submit of the form.
* Use a generic "edit" link since this name is too generic (but that's what the user story is asking to).
=> 8287 - Edit your contributions page (step 2)

HISTORY.md, README.md, lib/wpcc/version.rb
This PR updates the version to 1.3.0 and also addresses documentation for the process of publishing the latest version to GO.
Paired with @tomas-stefano !! :)
Easy to read view of README update:
=> Version documentation

app/views/wpcc/shared/_your_details.html.erb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/your_contributions_steps.rb, features/support/ui/your_contributions.rb
There was duplicate code for the your details section on the Your Contributions view and the Your Results view. This pr moves the duplicated code into its own partial.
=> [DEV APPROVED] Move shared markup into a partial

features/step_definitions/your_details_section_steps.rb
This pr addresses the second acceptance critierion for [TP User Story 8284](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8284/silent).
When Internationalisation is fully implemented, this scenario will be updated for the Welsh language.
=> [DEV APPROVED] - Test for full pay contribution scenario

README.md, package.json, test.sh
Some errors were raising before AND on this PR it is fixed. This are the problems that were raising:
1) When you run the karma tests using:
`karma start spec/javascripts/karma.conf.js --single-run`
The results:
`"Cannot load browser "PhantomJS": it is not registered! Perhaps you are missing some plugin?"`
Add the phantom js launcher to package json solves the issue.
2) The karma command was not running at all. Add karma and karma cli to the project instead relying on global packages. Before the code was expecting for the karma & karma-cli to be installed globally. Seting up for the project local specific makes the karma command to run using the right libraries from node_modules dir.  
I Added to the Readme the instructions to run the tests and install npm.
=> Fix karma specs

app/assets/javascripts/wpcc/require_config.js.erb, app/assets/stylesheets/wpcc/application.scss, app/assets/stylesheets/wpcc/components/_all.scss, app/assets/stylesheets/wpcc/components/_popup-tip.scss, app/assets/stylesheets/wpcc/components/_tooltip.scss, app/assets/stylesheets/wpcc/section/_details.scss, app/views/wpcc/shared/_popup_tip_close.html.erb, app/views/wpcc/your_details/new.html.erb, config/locales/cy.yml, config/locales/en.yml
Ticket [8380](https://moneyadviceservice.tpondemand.com/entity/8380)
This PR adds the tooltips component to the your details section of the tool.
- Popup tooltip component is added to dough
- MAS styles have been added to Yeast
Please note that the SVG icon for close wont appear using the dummy app, as they exist in frontend, so mount the app to see them.
| Screenshot |
|-------------|
|<img src="https://user-images.githubusercontent.com/13165846/28206760-14d0e1fe-687f-11e7-8fce-90916b9b4104.png" width="400" />|
| Screenshot |
|------------|
|![image](https://user-images.githubusercontent.com/13165846/28206867-864a050e-687f-11e7-946b-cbd07a086b1f.png)|
=> 8380 : add tooltips

Gemfile, app/controllers/wpcc/engine_controller.rb, test.sh
TP: https://moneyadviceservice.tpondemand.com/entity/8440
Since we're manipulating the session on the wpcc tool, it is necessary to add a security scanner to our tool.
On the ruby community one that is common used is brakeman: https://github.com/presidentbeef/brakeman
=> [DEV APPROVED] 8440 add security scanner

README.md, app/views/layouts/wpcc/engine.html.erb, lib/wpcc/engine.rb
**Problem**
The frontend application on uat was not loading the necessary javascripts file to run the wpcc tool.
**Solution**
After me and @willhall88 passed *hours* investigating why the frontend app was not loading the wppc require_config: https://github.com/moneyadviceservice/wpcc/blob/master/app/assets/javascripts/wpcc/require_config.js.erb
**We found that the frontend app is using a html attribute called "data-engine" that uses to search the key located on the require js.**  So if we define wpccConfig as key definition on *frontend* we need to define on *the engine* the data-engine=wpcc.
The key definitions: https://github.com/moneyadviceservice/frontend/blob/master/app/assets/javascripts/require_config.js.erb#L81
Loading those definitions: …
=> [DEV APPROVED] TP8435  - Add all the steps to load all the javascript wpcc components

Gemfile, app/controllers/wpcc/engine_controller.rb, spec/controllers/your_details_controller_spec.rb
* addresses [TP user story 8443](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8443/silent).
* ensures the session expires after 30 minutes if there has been no engagement with the tool.
A wpcc specific expiry session key is used to determine whether or not the session should be cleared. This approach ensures that the wpcc session does not conflict with or reset session expiry time which a user coming from the frontend site may be bringing. Refer to @tomas-stefano's comment below.
=> [DEV APPROVED] Expire session after 30 minutes

app/controllers/wpcc/engine_controller.rb, spec/controllers/your_details_controller_spec.rb, spec/dummy/config/application.rb
This pr fixes a bug introduced by pr #53.
The session expiry time was only being updated if the expiry time had not passed. Consequently, once the expiry time had passed, it would never be updated. The fix is to remove the condition and always update the session expiry time.
=> Always update session expiry time

app/assets/stylesheets/wpcc/base/_section.scss, app/assets/stylesheets/wpcc/section/_results.scss, app/controllers/wpcc/your_details_controller.rb, app/controllers/wpcc/your_results_controller.rb, app/presenters/wpcc/period_contribution_presenter.rb, app/presenters/wpcc/presenter.rb, app/presenters/wpcc/your_details_form_presenter.rb, app/views/wpcc/shared/_your_details.html.erb, app/views/wpcc/your_results/_frequency_selector_form.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, config/routes.rb, features/step_definitions/your_results_frequency_selector_steps.rb, features/support/ui/your_results.rb, features/your_results_frequency_selector.feature, spec/controllers/your_results_controller_spec.rb, spec/presenters/presenter_spec.rb, spec/presenters/your_details_form_presenter_spec.rb
This pr addresses [TP User Story 8406](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8406).
BLOCKED - waiting on welsh translation
* It adds a dropdown form to the your_results page to allow the user to change the salary_frequency for which the results are calculated.
* It refactors how we use presenters to have one presenter which handles the view_context and all other presenters inherit from this 'global' presenter.
=> [DEV APPROVED] 8406 frequency selector

app/assets/javascripts/wpcc/components/SalaryConditions.js, app/assets/javascripts/wpcc/require_config.js.erb, app/assets/stylesheets/wpcc/base/_wpcc.scss, app/assets/stylesheets/wpcc/section/_details.scss, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/javascripts/fixtures/SalaryConditions.html, spec/javascripts/test-main.js, spec/javascripts/tests/SalaryConditions_spec.js
[**8436**](https://moneyadviceservice.tpondemand.com/entity/8436)
Workers who earn under £5876 are not automatically opted into a workplace pension scheme. Although their employer is obliged to let them join the scheme if they choose, they are not obliged to make contributions.
[**8437**](https://moneyadviceservice.tpondemand.com/entity/8437)
Automatic enrolment into a pension scheme only applies to workers earning over £10,000, aged 22-State Pension age.
Users earning less can opt-in but will not be auto enrolled.
| Salary Below £5876 |
|------|
| First radio disabled, employer radio selected, callout displayed + State saved to local storage for use in step 2, callout also displayed above radio options |
|![image](https://user-images.githubusercontent.com/13165846/28567376-016128aa-712a-1 …
=> [DEV APPROVED] 8436 & 8437 Salary Conditional Messaging

app/controllers/wpcc/your_contributions_controller.rb, app/controllers/wpcc/your_details_controller.rb, app/controllers/wpcc/your_results_controller.rb, app/helpers/wpcc/home_helper.rb, app/models/wpcc/salary_message.rb, app/presenters/wpcc/message_presenter.rb, app/views/wpcc/shared/_your_details.html.erb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_results/index.html.erb, features/manually_opt_in_message.feature, features/step_definitions/manually_opt_in_message_steps.rb, spec/controllers/your_contributions_controller_spec.rb, spec/controllers/your_details_controller_spec.rb, spec/models/salary_message_spec.rb
This pr refactors the original approach I took to address [TP User Story 8427](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8427/silent).
This approach creates:
* a SalaryMessage class to be responsible for the conditional messages.
* a MessagePresenter to wrap the SalaryMessage instance.
Controllers needing to display conditional messages, should:
* instantiate a SalaryMessage with the appropriate message
* wrap it in a MessagePresenter instance
* assign to a variable for use by the view
=> Refactor 8427

app/assets/javascripts/wpcc/components/SalaryConditions.js, spec/javascripts/tests/SalaryConditions_spec.js
Fixes issue where the user enters a salary which results in a callout being displayed, and then changed the frequency.  The function to calculate the annual salary now runs when the frequency is changed, to ensure that the correct callouts are displayed/hidden.
=> [DEV APPROVED] - Fixes Frequency Change issue with salary based conditional messaging

app/assets/javascripts/wpcc/components/ContributionConditions.js, app/assets/javascripts/wpcc/require_config.js.erb, app/views/wpcc/your_contributions/new.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/javascripts/fixtures/ContributionConditions.html, spec/javascripts/test-main.js, spec/javascripts/tests/ContributionConditions_spec.js
Tax relief is only applied to contributions of up to £40,000 per year or 100% of your earnings, whichever is lower.
When I select any % that would result in an annual pension contribution of more than £40,000
Then I should be told that my proposed contribution is greater than the maximum allowed for tax relief and submit button should be disabled.
TP [ticket](https://moneyadviceservice.tpondemand.com/entity/8449)
=> [DEV APPROVED] 8449 - Contributions Conditions Component

app/models/wpcc/your_details_form.rb, app/views/wpcc/your_results/index.html.erb, features/_your_results/tax_relief_warning.feature, spec/models/your_details_form_spec.rb
This pr addresses a bug on [TP user story 8426](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8426/silent).
* Move the tax relief warning message to be positioned above the results table.
* Fix calculations for weekly salaries.
The YourDetails form was validating the salary to be an integer, which was preventing the form being submitted if a float was entered. The validation was changed to check for positive numbers only.
=> [DEV APPROVED] - 8426 Amendments to tax relief warning

app/assets/stylesheets/wpcc/print.scss
This fixes the issue on the results view where extra content (contact panels) was being printed. This is now excluded on the print stylesheet.
=> [WIP] - TP: 8214, Comment: Adds contact panels to exclusion on print stylesheet

app/models/wpcc/period_contribution_calculator.rb, app/models/wpcc/salary_frequency_converter.rb, config/salary_frequency_conversions.yml, features/_your_results/limit_tax_relief.feature, features/step_definitions/your_contributions_steps.rb, features/step_definitions/your_details_steps.rb, spec/models/contributions_calendar_spec.rb, spec/models/period_contribution_calculator_spec.rb
TP: https://moneyadviceservice.tpondemand.com/entity/8407
This PR adds the feature of where an employee contribution percentage amounts to an annual contribution greater than £40,000 the results page should limit annual tax relief to £8000 (20% of £40,000).
This PR also addresses other frequencies as well.
=> 8407 limit tax relief

app/views/wpcc/your_details/new.html.erb
A recent update has been made to the tooltip component in dough, as a result the markup to use the component has been changed.
This PR updates the markup for the tooltips in the your details section.
The original dough PR is [here](https://github.com/moneyadviceservice/dough/pull/288)
Please note that the version of dough in frontend will need to be bumped, this will be done as soon as this PR is merged.
=> Updates markup for updated tooltip dough component

HISTORY.md, lib/wpcc/version.rb
In order to deploy the wpcc to a secret url in production I think now we need to return to do the bump versions, since the tool is going to production.
This PR addresses the latest master version.
But please do not merge this PR until #94 is merged to master (but it is free to review)
=> Bump version from 1.4.0 to 1.5.0

app/views/wpcc/tooltips/_close.html.erb, config/locales/cy.yml, spec/dummy/config/application.rb
I was developing the user story of deploying the secret url to production ([here](https://moneyadviceservice.tpondemand.com/entity/8460)) and my tests were not passing due to missing translations keys.
1) make the tests catch those translation errors, from now on.
1) Fix the error ` translation missing for: cy.wpcc.results.period_title.april_2017_march_2018`
2) Fix the error `translation missing: cy.wpcc.details.tooltip_hide`
=> [DEV APPROVED] Fix "translation missing" errors

app/models/wpcc/your_details_form.rb, app/views/wpcc/your_details/new.html.erb, features/_your_details/your_details_disabling_minimum_contributions.feature, features/step_definitions/your_details_steps.rb, spec/models/your_details_form_spec.rb
This pr addresses [Tp User Store 8459](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8459/silent).
**This is for users without access to javascript**
* On first visiting the form, the minimum contribution_preference radio button is pre-checked.
* If the user has entered a salary below the minimum threshold and has selected the minimum contribution_preference radio button, on submission of the form, he will be returned to the form and the full contribution preference radio button will be checked.
* The minimum contribution_preference radio button will NOT be disabled as doing so would result in a poor experience for …
=> 8459 Select 'full salary' contribution preference

app/presenters/wpcc/your_details_form_presenter.rb, app/views/wpcc/your_details/new.html.erb, config/locales/cy.yml, config/locales/en.yml, features/_your_details/your_details_disabling_minimum_contributions.feature, features/step_definitions/your_details_steps.rb, features/support/ui/your_details.rb, spec/presenters/your_details_form_presenter_spec.rb
This pr addresses [TP User story 8477](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8477/silent). The requirements of this story changed during the course of completing it, please be sure to read the comments on the card.
A user should not be allowed to enter a  a salary below the minimum threshold AND select the minimum contribution option. The UI needs to communicate why he will be not allowed to proceed to Step 2 if he enters that combination.
Since all the callout messages are already present in the markup though hidden from view:
* a presenter method is used to change the class of the callout message to active …
=> [DEV APPROVED] 8477 - Display the salary below threshold callout message

config/locales/cy.yml, config/locales/en.yml, spec/presenters/period_contribution_presenter_spec.rb
1)  Delete [per year/per month/per 4 weeks/per week]
2)  Amend Results page heading so the first box always says ‘Now’
3) Change the current description under results
TP [Ticket](https://moneyadviceservice.tpondemand.com/entity/8491)
=> [DEV APPROVED] 8491 - Updates copy in the results page

app/assets/stylesheets/wpcc/section/_contributions.scss, config/locales/cy.yml, config/locales/en.yml
- Adds '%' outside the boxes to ensure it is clear what unit users are entering
- reduces the width of the boxes to allow 3 digits to be input
Addresses [TP8492](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8439&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8492)
Current: 
This PR:
=> TP: 8492, Comment: Step 2, updates percent boxes:

app/presenters/wpcc/presenter.rb, app/presenters/wpcc/your_contribution_presenter.rb, app/views/wpcc/your_contributions/new.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/presenters/your_contribution_presenter_spec.rb
Because part salary uses the concept of 'qualifying earnings', the text that displays for users who selected 'full salary' is somewhat misleading because contributions are then based on salary - not qualifying earnings.
As such we need this intro text to be conditional.
TP [Ticket](https://moneyadviceservice.tpondemand.com/entity/8472)
Use session data to determine the selected `contribution_preference` from step 1.
Display a message depending on the selection.
Hide logic from view using presenters.
Write cucumber tests. <--- @thecountgs _tests were written in RSpec in the end rather than in Cuke_
=> [DEV APPROVED] 8472 - Conditional messaging step 2

app/assets/javascripts/wpcc/components/SalaryConditions.js, spec/javascripts/fixtures/SalaryConditions.html, spec/javascripts/tests/SalaryConditions_spec.js
Addresses issues in [TP8505](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8439&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=Bug/8505)
Changes in the salary field were effecting the state of the contributions selector without user input. 
This PR:
- Adds a method to save the contribution state on page load and when this is changed by the user
- Uses this conditionally when changes are made to salary amount
=> [DEV APROVED] TP: 8505, Comment: Fixes bug on Step 1 re salary/contributions inputs

HISTORY.md, lib/wpcc/version.rb
Tp stories including on this version:
```
* TP-8505: Fixes bug on Step 1 re salary/contributions inputs
* TP-8472: Conditional messaging for step 2
* TP-8492: Step 2, updates percent boxes
* TP-8491: Updates copy in the results page
* TP-8448: Session expired redirect
* TP-8492: Step 3, updates percent boxes
* TP-8471: step 1 updates
* TP-8434: Information table of annual percents
* TP-8477: Display the salary below threshold callout message
* TP-8459: Select 'full salary' contribution preference
```
=> Bump version from 1.5.1 to 1.6.0

Gemfile, app/assets/javascripts/wpcc/components/UpdateResults.js, app/assets/javascripts/wpcc/require_config.js.erb, app/assets/stylesheets/wpcc/section/_results.scss, app/models/wpcc/period_contribution_calculator.rb, app/presenters/wpcc/period_contribution_presenter.rb, app/presenters/wpcc/presenter.rb, app/views/wpcc/your_results/_contributions_table.html.erb, app/views/wpcc/your_results/_frequency_selector_form.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/support/env.rb, features/your_results_frequency_selector.feature, spec/javascripts/fixtures/UpdateResults.html, spec/javascripts/test-main.js, spec/javascripts/tests/UpdateResults_spec.js, spec/models/period_contribution_calculator_spec.rb, spec/presenters/period_contribution_presenter_spec.rb, spec/presenters/presenter_spec.rb
On the Results Step this deals with the client-side updating of the results when the period selector is changed.
=> TP: 8439, Comment: Dynamically update values on results page

app/assets/javascripts/wpcc/components/ContributionConditions.js, spec/javascripts/tests/ContributionConditions_spec.js
The eligible salary amount has been changed to display the  currency symbol "£" within the figure rather than it being a static part of the view. This is preventing the amount which is displayed as text, to be parsed with jquery into an integer.
Use regex to remove the "£" symbol and the comma from the eligible salary string.
Use `parseInt` to convert to integer.
=> [DEV APPROVED] 8522 - Fixes contribution conditional messaging does not trigger

app/controllers/wpcc/your_results_controller.rb, app/models/wpcc/contributions_calendar.rb, app/models/wpcc/your_contributions_form.rb, app/presenters/wpcc/period_filter_presenter.rb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/_your_results/message_based_on_contribution_percents.feature, features/step_definitions/your_contributions_steps.rb, features/step_definitions/your_results_steps.rb, features/support/ui/your_results.rb, spec/models/contributions_calendar_spec.rb, spec/presenters/period_filter_presenter_spec.rb
This pr addresses [TP User Story 8506](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8506).
Additional messages need to be displayed on the results page to explain to the user how his results are calculated. These messages will vary depending on what he inputs for contribution percents.
* Expose the PeriodFilter to the view
* Create an additional presenter which gives us access to the user input contribution percents.
* Convert the percents to floats instead of integers
* There is one complex method which is used to display the correct message which we tried to refactor and abstract from the view.
=> 8506 Display messages based on contribution percents

app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml
**Task 1:** 
The section 'Next steps' heading is missing Welsh. 
**Task 2:** 
Add links to the 'Next steps' section on the results page. 
**Task 3:**
Step 1 of WPCC has Next button with missing welsh translation. 
**Bonus**
In the summary of Step 2, we have Welsh translation missing for "you" and "your employer".
TP [Ticket](https://moneyadviceservice.tpondemand.com/entity/8520)
=> [DEV APPROVED] 8520 - Results page links and welsh text in views

app/controllers/wpcc/your_results_controller.rb, app/models/wpcc/salary_frequency.rb, app/models/wpcc/salary_frequency_converter.rb, app/presenters/wpcc/period_contribution_presenter.rb, app/views/wpcc/your_results/_contributions_table.html.erb, config/locales/cy.yml, config/locales/en.yml, config/salary_frequency_conversions.yml, features/_your_results/displaying_frequency.feature, features/step_definitions/your_results_steps.rb, features/support/ui/your_results.rb, spec/controllers/your_results_controller_spec.rb, spec/models/salary_frequency_spec.rb, spec/presenters/period_contribution_presenter_spec.rb
This pr addresses [TP User Story 8507](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8507/silent). Specifically, the headings for Your, Employer and Total contributions on the results views should include the salary_frequency for example:
* Your annual contributions
* Employer's annual contributions
* Total annual contributions
We decided to add additional values to the salary_frequency config file to facilitate the english and welsh terminology that is required to display on the view. Please see the commit message for more technical detail.
=> 8507 Display frequency in results table headings

README.md
This pr removes some text from the readme. We initially added a checklist for various checkpoints in the build up to launching the tool. We're not using this checklist so it makes sense to remove it.
=> Remove redundant copy

app/presenters/wpcc/presenter.rb, app/presenters/wpcc/your_contribution_presenter.rb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/presenters/presenter_spec.rb, spec/presenters/your_contribution_presenter_spec.rb
This pr addresses [TP USER Story 8524](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8524).
Format the numbers on the views with a currency sign and the correct number of decimal places.
Please see the commit messages for the approach taken.
=> 8524 format numbers

app/assets/stylesheets/wpcc/application.scss
This is being caused because we are using the layout and tool CSS from yeast within the project, this is so we could preview the spacing and layout in the dummy app.  Sounds great but means that one of our required class attributes were being overwritten by some css being delivered *after* those in frontend.
| Before |
|--------|
|<img width="1405" alt="before" src="https://user-images.githubusercontent.com/13165846/29670812-c47d006c-88df-11e7-8cb6-09a845882ef8.png">|
|After |
|-----|
|<img width="1440" alt="after" src="https://user-images.githubusercontent.com/13165846/29670834-d52f2c8c-88df-11e7-8a59-38a70b967965.png">|
=> Fixes the issue with the global nav not being full width at full screen

app/controllers/wpcc/your_details_controller.rb, app/filters/wpcc/session_resetter.rb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, config/routes.rb, features/_your_results/reset_calculator.feature, features/step_definitions/your_details_steps.rb, features/step_definitions/your_results_steps.rb, features/support/ui/your_results.rb, spec/filters/session_resetter_spec.rb
This pr addresses [TP User Story 8408](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8408/silent).
Give the user the option to clear the data he has input in the Step 1 form. If the user is using the tool on a shared machine it allows him to reset the form so any sensitive data can't be viewed by the next user. 
* In the view, add a link which goes to the your_details_controller destroy action.
* Add a before filter, SessionResetter, to the your_details_controller destroy action.
* A new 'filter', SessionResetter, expires the session and redirects to the your_details new action.
=> [DEV APPROVED] 8408 Reset the calculator

app/assets/stylesheets/wpcc/section/_details.scss, app/views/wpcc/your_details/new.html.erb, lib/wpcc/version.rb
- Tidies the markup
- Corrects popuptip location for salary and contributions sections
Examples:
| Before | After |
|--------|------|
|![image](https://user-images.githubusercontent.com/13165846/29826262-c1f8f498-8cce-11e7-84e2-2ff1be95feea.png)|![image](https://user-images.githubusercontent.com/13165846/29826214-9ddc7a3a-8cce-11e7-903b-75664f424a9a.png)|
| Before | After |
|-------|------|
|![image](https://user-images.githubusercontent.com/13165846/29826488-58b539fa-8ccf-11e7-96bd-5ae1c910d3bb.png)|![image](https://user-images.githubusercontent.com/13165846/29826550-73f5d814-8ccf-11e7-93b6-ab8120c1ab91.png)|
=> Tidying markup

app/assets/javascripts/wpcc/components/Email.js, app/assets/javascripts/wpcc/require_config.js.erb, app/views/layouts/wpcc/engine.html.erb, app/views/wpcc/shared/_your_details.html.erb, app/views/wpcc/your_results/_contributions_table.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/javascripts/fixtures/Email.html, spec/javascripts/test-main.js, spec/javascripts/tests/Email_spec.js
This creates the component specified in [TP8213](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8507&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8213) which gives the user the ability to email their results via a mail client. 
On the results page a link is added: 
This launches the user's mail client pre-populated with the results:
=> [DEV APPROVED] TP: 8213, Comment: Adds email component

app/assets/javascripts/wpcc/components/UpdateResults.js, app/presenters/wpcc/period_contribution_presenter.rb, app/presenters/wpcc/presenter.rb, app/views/wpcc/your_results/_contributions_table.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/javascripts/fixtures/UpdateResults.html, spec/javascripts/tests/UpdateResults_spec.js, spec/presenters/period_contribution_presenter_spec.rb, spec/presenters/presenter_spec.rb
The salary_frequency adjective is required by the js to update the contribution headings when the salary frequency is changed.
=> [DEV APPROVED] Add a data attribute to the salary_frequency selector form

config/locales/en.yml
Refer to #127, the warning should read 'This tool is in Beta', not 'This is tool is in Beta'
=> [DEV APPROVED] Update translation file

app/assets/javascripts/wpcc/components/UpdateResults.js, app/presenters/wpcc/period_contribution_presenter.rb, app/presenters/wpcc/presenter.rb, app/views/wpcc/your_results/_contributions_table.html.erb, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/your_results_steps.rb, spec/javascripts/fixtures/UpdateResults.html, spec/javascripts/tests/UpdateResults_spec.js, spec/presenters/period_contribution_presenter_spec.rb, spec/presenters/presenter_spec.rb
As a user trying to work out the impact of my contributions on my take-home pay I need to see the frequency that is being displayed clearly on my results so that I fully understand what I will be paying and how often.
[TP](https://moneyadviceservice.tpondemand.com/entity/8526)
Add a word to indicate frequency within each results table to indicate what frequency the figure is displaying.
Attach the `data-frequency-adjective` value generated by back end logic to a js object.
Update titles by targeting `data-dough-title-frequency` rendered into the view from our yaml file.
|English    |  Welsh |
|--------- |-------- |
|<img src="https://user-images.githubusercontent.com/2187295/29931166-5d606e1c-8e68-11e7-878f-66cd506d4e88.png"> | <img …
=> [DEV APPROVED] 8526 - Frontend/Backend Frequency titles in results table

app/views/wpcc/your_details/new.html.erb, config/locales/cy.yml, config/locales/en.yml, lib/wpcc/version.rb
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8531)
- Updates the salary input label to read "Your Salary" in English and "Eich cyflog" in Welsh
- Updates tooltip copy to read:
En:
"Enter your salary before tax or other deductions are taken off.  This is known as your gross salary.  If you have more than one job, you will have to enter each salary separately."
Cy:
"Rhowch eich cyflog cyn i’r dreth nag unrhyw ddidyniadau eraill gael eu tynnu. Gelwir hyn yn gyflog gros.  Os oes gennych fwy nag un swydd, bydd raid i chi roi pob cyflog ar wahân."
**Screenshots**
| English | Welsh |
|--------|--------|
|![image](https://user-images.githubusercontent.com/13165846/30019995-3e371bae-915a-11e7-8a87-ce80529b4756.png)|![image](https://user-images.githubusercontent.com/13165846/30020017-5 …
=> [DEV APPROVED] 8531 - WPCC: Amend Salary label and Salary tooltip

app/forms/wpcc/object_error.rb, config/locales/cy.yml, config/locales/en.yml
[TP Card](https://moneyadviceservice.tpondemand.com/entity/8458)
This PR fixes an issue where an incorrect validation message was being displayed for the ages over 75.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/wpcc/132)
=> [DEV APPROVED] 8458 - Corrects the i18n key for age validation

app/assets/javascripts/wpcc/components/SalaryConditions.js, app/views/wpcc/your_details/new.html.erb, config/locales/en.yml
1 - The salary conditional message for not being automatically enrolled does not trigger for a salary of £10,000 per year. 
2 - The Salary conditional message for users between £5876 - £10,000, inclusive, uses the spelling 'enroll'. This should be 'enrol'
3 - If I enter a salary under £5876 per year, the warning above the 'part salary/full salary' selection does not appear, and the 'part salary' button is not disabled, as per the ticket 8436
Increase `annualSalary`ceiling from `9999` to `10000`.
Fix spelling in yaml file.
Nest the salary and employer contribution sections within the `SalaryConditions` dough component.
| Bug 1 - 2 | Bug 3|
| ---------| -------|
|<img alt="screen shot 2017-09-04 at 14 30 16" src="https://user-images.githubusercontent.com/2187295/30028663-d6ca18c6-917d-11e7-8 …
=> 8552 - Client side step 1 errors

config/locales/cy.yml, config/locales/en.yml
This pr addresses [TP User Story](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8555/silent).
The content team have provided a new url to be linked to in the tooltip for information about the salary field on the form on Step 1. This pr updates the url accordingly.
=> [DEV APPROVED] 8555 - Amend url for salary tooltip

HISTORY.md, app/views/wpcc/your_details/new.html.erb, lib/wpcc/version.rb
Due to front end refactoring the last two Popuptips are displaying together when either of them are triggered.
Float issue in view
- The `Popuptip` dough component is now assigned individually to to each trigger.
- `details__row--group` is assigned to the parent of the entire section and removed from the salary contribution radio buttons.
=> 8556 - Fixes bug in step 1 view

app/views/wpcc/your_results/_contributions_table.html.erb, spec/javascripts/fixtures/Email.html
Refers to [TP8213](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=userstory/8213) (see latest comment).
Some headings were not apparent in the email string due to missing attributes in the markup: 
These have been replaced so the message is as expected:
=> [DEV APPROVED] TP: 8213, Comment: Fixes issues with email message

app/assets/javascripts/wpcc/components/ContributionConditions.js
An issue was discovered where regex in `ContributionConditions` component was being improperly compiled in the asset pipeline. This prevented the component from working.
[TP](https://moneyadviceservice.tpondemand.com/entity/8563)
**Output after compilation:**
this.$eligibleSalary.text().replace(/[\\xa3,]/g, "")
**Original regex call:**
this.$eligibleSalary.text().replace(/[\£,]/g, ''),
**The regex change lead to the £ symbol not being removed from the string which caused the script to return Nan:**
Salary number: £100000
Salary to number: Nan
salaryContributionAmount: Nan
Remove `/` character from the component regex string. This character was being improperly parsed by the asset pipeline, which caused the component to not function properly.
=> [DEV APPROVED] 8563 - Fixes regex compilation bug in step 2

app/assets/javascripts/wpcc/components/UpdateResults.js, app/presenters/wpcc/period_contribution_presenter.rb, app/views/wpcc/your_results/_contributions_table.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/javascripts/fixtures/UpdateResults.html, spec/javascripts/tests/UpdateResults_spec.js, spec/presenters/period_contribution_presenter_spec.rb
This pr addresses [TP User Story 8551](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=DDD7F3A626844AB8D1BEE3F06EC28EFA#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8551).
Include the welsh translation for the text 'includes tax relief'.
* Amend the presenter to get the text from the translation file rather than include the text in the presenter
* Add a span to the translation to enable the javascript to update the tax-relief amount when the salary_frequency is changed.
=> [DEV APPROVED] 8551 Add Welsh translation for tax-relief

app/controllers/wpcc/your_contributions_controller.rb, app/controllers/wpcc/your_results_controller.rb, app/models/wpcc/salary_message.rb, app/presenters/wpcc/message_presenter.rb, app/views/wpcc/shared/_your_contributions.html.erb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/_your_results/contributions_above_maximum_message.feature, features/step_definitions/your_details_steps.rb, features/step_definitions/your_results_steps.rb, spec/controllers/your_contributions_controller_spec.rb, spec/controllers/your_results_controller_spec.rb
This pr addresses [TP User Story 8299](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=DDD7F3A626844AB8D1BEE3F06EC28EFA#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8299/silent).
If employee_contributions are above the amount for which tax relief is applicable, display an appropriate message in the your_contributions section on the results view.
* new method in SalaryMessage to make this check
* method in messagePresenter which gets the translation text using the max amount
* correct figure to pass to the translation
* move your_contributions markup in your_results view into a partial
=> [DEV APPROVED] 8299 Tax relief warning message

app/presenters/wpcc/period_filter_presenter.rb, features/_your_results/message_based_on_contribution_percents.feature
TP: https://moneyadviceservice.tpondemand.com/entity/8506
Context
The tables on step 3 appear based on the % contribution set by the user while completing the tool, depending on the % selected by the user and what is minimum % set by the govt. This feature is about displaying a message when the user contributes more, depending on the % the user added.
Fixes 
When this was developed the figures were followed on what it was written on the card. After it was realized that the figures were wrong because was not just greater than. The correct is greater than or equal in *some* comparisons, as you can see below (all this scenarios are on cucumber features too):
Scenario 1
When an Employee and an Employer, both contributing more than the minimum
increase for 2018 AND 2019
Employee contribution …
=> [DEV APPROVED] Fix messages based on the displayed results table

HISTORY.md, app/assets/javascripts/wpcc/components/ConditionalMessaging.js, app/assets/javascripts/wpcc/components/ContributionConditions.js, app/assets/javascripts/wpcc/components/Email.js, app/assets/javascripts/wpcc/components/SalaryConditions.js, app/assets/javascripts/wpcc/components/UpdateResults.js, app/views/wpcc/shared/_your_contributions.html.erb, app/views/wpcc/shared/_your_details.html.erb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, app/views/wpcc/your_results/_contributions_table.html.erb, app/views/wpcc/your_results/_frequency_selector_form.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/support/ui/your_details.rb, lib/wpcc/version.rb, spec/javascripts/fixtures/ConditionalMessaging.html, spec/javascripts/fixtures/ContributionConditions.html, spec/javascripts/fixtures/Email.html, spec/javascripts/fixtures/SalaryConditions.html, spec/javascripts/fixtures/UpdateResults.html, spec/javascripts/tests/ConditionalMessaging_spec.js, spec/javascripts/tests/ContributionConditions_spec.js, spec/javascripts/tests/Email_spec.js, spec/javascripts/tests/SalaryConditions_spec.js, spec/javascripts/tests/UpdateResults_spec.js, spec/presenters/period_contribution_presenter_spec.rb
We had a conversation about the naming of some of our dough component element selectors.  We currently use ``data-dough-component="ComponentName"`` to specify a component.  And then within the component we use similar selectors to select elements used in the component (eg.. ``data-dough-salary-input``).
This has raised the question regarding how clear this approach is to anyone reading the code, using the current format (in the example above), it suggests that the component is strictly a dough component and lives within dough.
The proposed solution is to refactor the selectors and attributes relating the the **internal** WPCC components (That dont live within dough itself):
- We would specify the dough component as we do now:
```
<div data-dough-component="ComponentName">
...
</div>
``` …
=> [DEV APPROVED] Refactors naming of data- attributes

app/models/wpcc/contributions_calendar.rb, app/models/wpcc/period.rb, features/_your_results/salary_below_minimum_threshold.feature, features/step_definitions/your_details_steps.rb, features/step_definitions/your_results_steps.rb, spec/models/contributions_calendar_spec.rb, spec/models/period_spec.rb
This pr addresses [TP User Story 8565](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=DDD7F3A626844AB8D1BEE3F06EC28EFA#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=UserStory/8565).
If the user's salary is below the minimum, use the user input; otherwise use the higher of the user's input and the legal requirement.
* The Period class sets the employer percent. I amended this class to first check the salary and then set the employer percent accordingly
* The ContributionsCalculator needs to call the new Period class method and pass the salary.
=> [DEV APPROVED] 8565 Amend the employer percent for calculating contributions

HISTORY.md, app/assets/javascripts/wpcc/components/SalaryConditions.js, app/models/wpcc/salary_message.rb, app/presenters/wpcc/message_presenter.rb, app/views/wpcc/your_contributions/new.html.erb, features/_your_contributions/percent_validation.feature, features/_your_contributions/your_contributions_calculating_qualifying_earnings.feature, features/step_definitions/your_contributions_steps.rb, features/step_definitions/your_details_steps.rb, lib/wpcc/version.rb, spec/javascripts/tests/SalaryConditions_spec.js, spec/models/salary_message_spec.rb, spec/presenters/message_presenter_spec.rb
[TP - 8564](https://moneyadviceservice.tpondemand.com/entity/8564) Step 2 Validation based on Salary
This PR addresses a change of logic from Client side to Server side. The need for this comes from the fact that WPCC is not a one page app as originally planned. 
When a user has a salary less than £5,876 the messages displayed in the contribution boxes are different as there is no longer a legal minimum of 1%
=> 8564 percent validation server side

HISTORY.md, config/locales/cy.yml, config/locales/en.yml, lib/wpcc/version.rb
[TP Ticket 8572](https://moneyadviceservice.tpondemand.com/entity/8572)
There are three links (listed below) in the WPCC tool, mostly referenced to articles, that open in the same tab; this kind of kills the user journey as the user is sent to those links from the tool.
This PR:
- Adds the target="_blank" attribute to these links
- Also adds visually hidden text for accessibility
=> [DEV APPROVED] 8572 - Updating links to open in new tabs

HISTORY.md, app/assets/stylesheets/wpcc/base/_forms.scss, lib/wpcc/version.rb
There is currently a dropdown issue on IE11 in WPCC.  This PR solves it
| Before |
|-------|
|![image](https://user-images.githubusercontent.com/13165846/30813611-cea8efda-a205-11e7-8acb-479476023474.png)|
| After |
|------|
|![screen shot 2017-09-25 at 15 22 28 2](https://user-images.githubusercontent.com/13165846/30813657-ebdc5da8-a205-11e7-85bd-b48e0ac9e4c9.png)|
=> [DEV APPROVED] 8580 - IE11 : Fixing the double dropdown issue

HISTORY.md, lib/wpcc/version.rb, spec/javascripts/tests/SalaryConditions_spec.js
This is now handled in the back end.  Currently 2 tests are failing on WPCC.  One checks that a local storage item is saved when a user enters a salary under £5876 and the other checks that this entry exists on step 2.
This functionality was moved into the backend in [this PR](https://github.com/moneyadviceservice/wpcc/pull/146) and is therefore no longer needs to be tested.
=> [DEV APPROVED] Removes Karma tests checking for local storage

features/step_definitions/your_contributions_steps.rb, features/step_definitions/your_details_steps.rb, features/support/hooks.rb, features/support/world/wait_for_page_load.rb
This PR should fix a race condition where sometimes javascript cucumbers fail because dough-ruby components have not yet loaded.
=> [DEV APPROVED] Add a delay in cukes for javascript files to load

app/controllers/wpcc/your_results_controller.rb, app/models/wpcc/contributions_calendar.rb, features/_your_results/salary_below_minimum_threshold.feature, features/step_definitions/your_results_steps.rb, lib/wpcc/version.rb, spec/controllers/your_results_controller_spec.rb, spec/models/contributions_calendar_spec.rb
This pr addresses [TP 8605](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/8605). It addresses a bug whereby an incorrect employer_percent is being used for the calculations of the second and third periods. This bug was only appearing for salaries initially entered as annual; it was not appearing for the other salary_frequencies e.g. monthly, weekly and 4-weekly.
__The tool is set up to show the monthly figures by default if the user enters an annual salary.__
The annual salary was being calculated in the Contributions Calendar, using  the __default salary frequency__ rather than the one stored in the session. Hence, why …
=> [DEV APPROVED] 8605 - Incorrect employer percent

config/locales/cy.yml, config/locales/en.yml
TP Ticket: [8609](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8608&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8609)
This PR is to correct a typo on the salary tooltip on the first view, specifically a space appearing before the comma after the link: 
This has been corrected in the English and Welsh versions:
=> [DEV APPROVED] TP: 8609, Comment: Corrects typo on salary tooltip

app/assets/javascripts/wpcc/components/Email.js, app/views/wpcc/your_results/_contributions_table.html.erb, spec/javascripts/fixtures/Email.html, spec/javascripts/tests/Email_spec.js
TP ticket: [TP8588](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8611&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/8588)
Adding the tooltip to the tax relief line in the results table has caused an error, meaning the tooltip trigger is included in the text that the user might send by email. 
This PR excludes that text when the email text is constructed, and updates the Karma tests to reflect this change.
**Before:**
**After:**
=> [DEV APPROVED] TP: 8588, Comment: Updates component and tests to exclude tooltip

app/assets/stylesheets/wpcc/components/_popup-tip.scss, app/assets/stylesheets/wpcc/section/_contributions.scss, app/assets/stylesheets/wpcc/section/_details.scss, app/assets/stylesheets/wpcc/section/_results.scss, app/presenters/wpcc/earnings_description.rb, app/presenters/wpcc/message_presenter.rb, app/views/layouts/wpcc/engine.html.erb, app/views/wpcc/tooltips/_content_qualifying_earnings.html.erb, app/views/wpcc/tooltips/_trigger.html.erb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, app/views/wpcc/your_results/index.html.erb, config/locales/cy.yml, config/locales/en.yml, features/_your_results/conditional_qualifying_earnings_message.feature, features/qualifying_earnings_tooltip.feature, features/step_definitions/qualifying_earnings_tooltip_steps.rb, features/step_definitions/your_details_steps.rb, lib/wpcc/version.rb, spec/presenters/message_presenter_spec.rb
TP ticket: [TP8610](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8609&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8610)
This work is to add a tooltip describing the concept of qualifying earnings to the relevant message in Steps 2 and 3 of the tool, as already exists in Step 1.
**Step 1:**
**Step 2 current: **
**Step 2 update: **
**Step 3 current: **
**Step 3 update: **
This involved a combination of back and front end work to implement an elegant solution because the tooltip trigger is rendered via a partial and the text message is rendered via a presenter which complicated an otherwise seemingly straightforward task.
=> [DEV APPROVED] TP8610, Adds tootips to Views 2 and 3

HISTORY.md, config/locales/cy.yml, lib/wpcc/version.rb
[TP 8634](https://moneyadviceservice.tpondemand.com/entity/8634)
| Before | After |
|--------|------|
|![image](https://user-images.githubusercontent.com/13165846/32046060-d5e9910e-ba39-11e7-942d-a0b0503e481c.png)|![image](https://user-images.githubusercontent.com/13165846/32046136-073dcdba-ba3a-11e7-9ea3-17df60d7ca9d.png)|
=> [DEV APPROVED] [BUG] Fixes missing tooltip for Welsh

app/assets/stylesheets/wpcc/section/_details.scss, app/views/layouts/wpcc/engine.html.erb, app/views/wpcc/shared/_your_contributions.html.erb, app/views/wpcc/shared/_your_details.html.erb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, app/views/wpcc/your_results/_frequency_selector_form.html.erb, app/views/wpcc/your_results/index.html.erb, lib/wpcc/version.rb
This PR addresses a number of accessibility fixed for WPCC as a result of the testing performed by DAC.
[8686](https://moneyadviceservice.tpondemand.com/entity/8686) 
```
On step 1 of the WPCC tool, the label for salary frequency has the 'visually-hidden' class (which is correct), but also has the class 'details__field-label'.
In the CSS, the .details__field-label {} contains visibility: hidden, making it invisible to screen readers.
Task: Remove 'visibility: hidden;' from the .details__field-label attributes in the CSS.
```
[8687](https://moneyadviceservice.tpondemand.com/entity/8687)
```
Missing contributions labels
There is currently no label for attribute present for the contributions step of the WPCC tool
Suggestion: To avoid adding repeated content, use the header of each section as …
```
=> [DEV APPROVED] - Ally fixes

HISTORY.md, lib/wpcc/version.rb
I missed something in the last deploy and my changes aren't present on the test environment, Im putting this down to versions and tags not being aligned.
This aims to fix this inconsistency
=> Bumps minor version for accessibility updates

HISTORY.md, app/views/wpcc/your_results/_period_percents_table.html.erb, config/locales/cy.yml, config/locales/en.yml, features/step_definitions/your_results_steps.rb, lib/wpcc/version.rb
[TP Ticket 8694](https://moneyadviceservice.tpondemand.com/entity/8694)
Tables must be made using appropriate mark-up to ensure that they are rendered properly by assistive technologies. 
Table headers should never be empty. This caused confusion for DAC screen reader analysts as it was not clear what the column was displaying without reading all of the content in the table.
The offending table is on the results step:
This PR adds a visually-hidden span which displays the correct header for both English and Welsh
=> [DEV APPROVED]WPCC | A11y - Results table heading

Gemfile, HISTORY.md, lib/wpcc/version.rb
```  
[jonesagyemang:~/Projects/MAS/wpcc] add-dangerfile(+16/-4)+* 1h56m55s ± ./test.sh
export RAILS_ENV=test
RAILS_ENV=test
export BUNDLE_WITHOUT=development
BUNDLE_WITHOUT=development
npm install -q
bundle install --quiet
bundle exec brakeman -q --no-pager --ensure-latest
Brakeman 4.0.1 is not the latest version 4.1.1
```
Brakeman is failing, as expected for, as it's not using the latest gem `4.1.1`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/wpcc/187)
=> [DEV APPROVED] - Updates Brakeman gem to prevent test scripts from failing

app/assets/javascripts/wpcc/components/SalaryConditions.js, app/concerns/wpcc/salary_threshold.rb, app/filters/wpcc/session_expirer.rb, app/models/wpcc/config_loader.rb, app/models/wpcc/contribution_calculator.rb, app/models/wpcc/period_contribution_calculator.rb, app/models/wpcc/period_filter.rb, app/models/wpcc/salary_frequency_converter.rb, app/models/wpcc/salary_message.rb, app/models/wpcc/your_details_form.rb, app/presenters/wpcc/message_presenter.rb, app/validators/wpcc/salary_threshold_validator.rb, app/views/wpcc/your_contributions/new.html.erb, app/views/wpcc/your_details/new.html.erb, config/session.yml, spec/javascripts/fixtures/SalaryConditions.html, spec/javascripts/tests/SalaryConditions_spec.js, spec/models/your_details_form_spec.rb
Tp: https://moneyadviceservice.tpondemand.com/entity/8446-wpcc-store-app-specific-settings
The Workplace Pension Contribution Calculator uses different approaches to store app-specific settings. This PR seeks to define and use one approach. 
Dough convention when loading components is every time
you have a component (e.g data-dough-component=SalaryConditions)
Dough will try to find an html attribute called 'data-dough' PLUS
the name of the component PLUS config (e.g data-dough-salary-conditions-config)
and parse the object and store in the config variable as the second
argument of the initialize function.
This PR uses that convention.
I decided to write the documentation task below to the technical docs repo. I will post the link soon.
=> [DEV APPROVED] 8446 store app specific settings

config/salary_frequency_conversions.yml, features/_your_results/tax_relief_warning.feature, spec/models/salary_message_spec.rb
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8903-wpcc-update-tax-relief-messaging)
This PR updates the cutoff value for the tax relief message to be `11850` instead of `11500`
**NB** This change is not due to go live until April, see the above linked TP card for details.
=> [DEV APPROVED] TP 8903: Updates the tax relief on salary breakpoint from 11500 to 11850

app/models/wpcc/period.rb, app/models/wpcc/period_filter.rb, config/locales/cy.yml, config/locales/en.yml, config/periods_legal_percents.yml, features/_your_results/calculating_different_salary_frequencies.feature, features/_your_results/contribution_above_legal_minimum.feature, features/_your_results/limit_tax_relief.feature, features/_your_results/message_based_on_contribution_percents.feature, features/_your_results/period_percent_table.feature, features/_your_results/salary_below_minimum_threshold.feature, features/step_definitions/your_results_steps.rb, features/support/ui/your_results.rb, features/your_results_frequency_selector.feature, spec/models/period_filter_spec.rb, spec/models/period_spec.rb, spec/presenters/period_contribution_presenter_spec.rb, spec/presenters/period_filter_presenter_spec.rb, spec/presenters/period_presenter_spec.rb
[TP 8906](https://moneyadviceservice.tpondemand.com/entity/8906-wpcc-remove-the-april-2018-19)
* Removes the box showing contributions for the 2018-2019 period. 
* Also makes some changes to the logic for period filtering. We always want to show the box with contribution amounts for the current period, but only want to show '2019 onwards' if percentages input by the user are lower than or equal to the 2019 thresholds.
_before_
_after_
We've commented out a couple of feature specs relating to the messaging shown on the results page about which contributions figures are being shown. The piece of work that will fix these specs is going to be handled in [8908](https://moneyadviceservice.tpondemand.com/entity/8908-wpcc-remove-conditional-messaging-on-the) which we're picking up next.
=> [DEV APPROVED] 8906: Remove 2018 to 2019 period contributions box

app/presenters/wpcc/period_filter_presenter.rb, config/locales/cy.yml, config/locales/en.yml, features/_your_results/message_based_on_contribution_percents.feature, spec/presenters/period_filter_presenter_spec.rb
[TP 8908](https://moneyadviceservice.tpondemand.com/entity/8908-wpcc-remove-conditional-messaging-on-the)
Updates the conditional messaging on the results page in line with the removal of the 2018-2019 contributions box. Includes:
* Removal of logic branch, translation and spec for scenario where users input percentage was above the 2018 minimum but NOT the 2019 minimum. 
* Renaming of translations and specs for the other scenarios to remove references to 2018 and the third contributions box which was removed in [8906](https://moneyadviceservice.tpondemand.com/entity/8906-wpcc-remove-the-april-2018-19)
=> [DEV APPROVED] 8908: Remove conditional messaging on results page

Gemfile
When running `test.sh`, brakeman currently fails as below
``` 
bundle exec brakeman -q --no-pager --ensure-latest
Brakeman 4.1.1 is not the latest version 4.2.0
```
This PR updates to the latest version
=> [DEV APPROVED] Updates brakeman gem version to latest

config/contribution_calculations.yml, spec/models/full_contribution_calculator_spec.rb
[TP 8994](https://moneyadviceservice.tpondemand.com/entity/8994-wpcc-update-contribution-percentages-for-full)
Updates the default contribution percentages for a user with a salary above the lower threshold who has selected to make contributions based on their full salary, to bring them in line with the legal minimum percentages for 2018-2019.
Also removes default contribution percentages for a user with a salary below the lower threshold based on minimum salary, as this is not a valid use case. A user can only select the 'part' salary option if their salary is above the threshold.
=> [DEV APPROVED] - 8994: Update default contribution percentages for pension contributions based on full salary

app/assets/javascripts/wpcc/components/SalaryConditions.js, app/presenters/wpcc/message_presenter.rb, app/views/wpcc/your_details/new.html.erb, config/locales/cy.yml, config/locales/en.yml, features/_your_contributions/your_contributions_calculating_qualifying_earnings.feature, features/_your_results/salary_below_minimum_threshold.feature, features/manually_opt_in_message.feature, features/near_lowest_pension_messages.feature, features/support/ui/your_details.rb, spec/javascripts/fixtures/SalaryConditions.html, spec/javascripts/tests/SalaryConditions_spec.js
[TP 8985](https://moneyadviceservice.tpondemand.com/entity/8985-refactorclean-wpcc-to-allow-for-easier)
This is the first part of some refactoring work in wpcc, being done as part of the new tax year changes.
This PR handles renaming js variables, wpcc-data attributes and translations to avoid referencing specific threshold values and instead use more generic references alluding to the use of the variables.
Additionally, removes `employeeTip` and `employerTip` from the js as the functionality for showing/hiding the correct tips is handled in `MessagePresenter`
=> [DEV APPROVED] 8985: Generalise variables and translations

HISTORY.md, lib/wpcc/version.rb
Work done on #205 
Since it is a big release that changes structural data I decided to bump to 2.0.0.
* Tax year changes for April 2018
* Refactor wpcc config yaml files
* Refactor javascript to be flexible with the threshold values that changes
each year.
=> Bump version to 2.0.0

README.md
Updating documentation since GO CI is not being used by the wpcc anymore.
Also remove whitespaces on Readme
=> Fix wrong CI link on Readme when releasing new version

Gemfile, app/views/wpcc/your_details/new.html.erb, lib/wpcc/version.rb
[TP9280](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/9280)
For SEO purposes the page title on the landing page of the WPCC tool is updated from "Your Details - Workplace pension contribution calculator - Money Advice Service" to "Workplace pension contribution calculator - Money Advice Service".
=> [DEV APPROVED] TP: 9280, Comment: Updates page title

Gemfile, app/assets/stylesheets/wpcc/components/_popup-tip.scss, lib/wpcc/version.rb
[TP9256](https://moneyadviceservice.tpondemand.com/entity/9256-bug-wpcc-callout-overlap)
The PR fixes a bug where the popup/callout was getting overlapped by updating the zindex
Before:
After:
=> [DEV APPROVED] 9256 Callout overlapped bug

jenkins/Dockerfile, jenkins/test, wpcc.gemspec
Use latest bundled image with gem sets pre-installed
- Update test script to go to error on test failure
- Reduces Jenkins test time from 6mins 40sec to 3mins 50secs
=> Use bundled image for Jenkins

app/assets/stylesheets/wpcc/section/_results.scss, app/views/wpcc/your_results/_contributions_table.html.erb
[TP-10292](https://moneyadviceservice.tpondemand.com/entity/10292-nty-wpcc-remove-results-block-for)
Results don't show an additional step up block anymore (explaining
future contributions).
As a consequence of that, the contributions block can be displayed
without a heading distinguishing between "Now" and "April 2019.."
contribution values. We have a single block containing the current
and onwards contribution values.
This work removes the green heading with the title of the block left
on the results.
=> [DEV APPROVED] TP-10292: Remove "green heading block" from results

Gemfile, app/assets/stylesheets/wpcc/section/_contributions.scss, app/presenters/wpcc/earnings_description.rb, app/presenters/wpcc/message_presenter.rb, app/views/wpcc/your_contributions/new.html.erb, config/locales/cy.yml, config/locales/en.yml, features/_your_contributions/percent_validation.feature, lib/wpcc/version.rb, spec/presenters/message_presenter_spec.rb, spec/shared_examples/earnings_description_shared_example.rb
To make it clear to users they can contribute less than the minimum percentage in some circumstances, the text has been altered and an additional tooltip added.
[TP-10440](https://moneyadviceservice.tpondemand.com/entity/10440-wpcc-text-changes-on-step-2)
=> [DEV APPROVED] 10440 Change text on Your Contributions

app/assets/javascripts/wpcc/components/ContributionsMinimumValidation.js, app/assets/javascripts/wpcc/require_config.js.erb, app/controllers/wpcc/your_contributions_controller.rb, app/views/wpcc/your_contributions/_minimum_contribution_error.html.erb, app/views/wpcc/your_contributions/new.html.erb, lib/wpcc/version.rb, spec/javascripts/fixtures/ContributionsMinimumValidation.html, spec/javascripts/test-main.js, spec/javascripts/tests/ContributionsMinimumValidation_spec.js
[TP 10504](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10504/silent)
To provide a better user experience and adhere to MAS usability standards, this pr adds client side validation for checking the contributions entered on step 2. Specifically the sum of the 2 fields should total at least 8.
=> [DEV APPROVED] 10504 Better validation of contributions

Gemfile, app/assets/stylesheets/wpcc/components/_popup-tip.scss, config/locales/cy.yml, config/locales/en.yml, lib/wpcc/version.rb, wpcc.gemspec
[TP 10508](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10508/silent)
1. Change the Employer contributions error message to be more reflective of what's required.
2. Adjust the tooltips to display on top of any conditional callout messages that may be displayed.
**MERGE/DEPLOY NOTES**
This pr is dependent on [dough pr 329](https://github.com/moneyadviceservice/dough/pull/329).
=> [DEV APPROVED] 10508 Improvements to Step 2 display

Gemfile, config/cucumber.yml, features/support/env.rb, jenkins/test, spec/rails_helper.rb
This repo does not use ActiveRecord and its models are not backed by a database.  
Therefore we disable Cucumber's auto-running of DatabaseCleaner after each example (else it will fail). 
Disable transactional_fixtures
Brakeman set to --no-exit-on-warn
Remove ~@ tags
=> TP 12179 Fix failing tests on NTT Branch

app/assets/javascripts/wpcc/components/ConditionalMessaging.js, app/views/wpcc/your_details/new.html.erb, config/config.yml, config/locales/cy.yml, config/locales/en.yml, features/_your_contributions/your_contributions_calculating_qualifying_earnings.feature, features/_your_details/age_validation.feature, features/manually_opt_in_message.feature, spec/javascripts/tests/ConditionalMessaging_spec.js, spec/models/minimum_contribution_calculator_spec.rb, spec/presenters/presenter_spec.rb
Ticket [TP-12632](https://maps.tpondemand.com/RestUI/Board.aspx#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiREI5QTI2RDFCNTJDN0JFNTQxMDRDRDIyN0ZFNDIzRDYifQ==&boardPopup=userstory/12632/silent)
Removed the tooltip from the gender field
Updated the messages related to the age and gender
Changed the rule for the age to 66 so the correct messages apply to age groups 15-21 & 66-74, <15, 74>
Removed the rules that was checking the gender to display the message
Updated the tests 
Ticket [TP-12642](https://maps.tpondemand.com/RestUI/Board.aspx#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiREI5QTI2RDFCNTJDN0JFNTQxMDRDRDIyN0ZFNDIzRDYifQ==&boardPopup=userstory/12642/silent)
Updated the links in salary tooltip as per the ticket
Also includes TP-12597.
=> 12632 state pension age triggers

jenkins/test, test.sh
These are failing due to some weird version mismatching.
=> Temporarily disable karma tests
