moneyadviceservice/wpcc

app/assets/javascripts/wpcc/components/ConditionalMessaging.js
app/assets/javascripts/wpcc/require_config.js.erb
app/assets/stylesheets/wpcc/_details.scss
app/assets/stylesheets/wpcc/application.scss
app/views/wpcc/your_details/new.html.erb
config/locales/cy.yml
config/locales/en.yml

This adds conditional messages to the landing page which depend on values entered for the age and gender fields. 
Example: 
Additionally it disables the submit button where the age range is below or above the relevant values.

[DEV APPROVED] TP: 8209, Comment: Adds conditional messages

---

app/assets/javascripts/wpcc/components/ConditionalMessaging.js
app/assets/stylesheets/wpcc/application.scss
app/assets/stylesheets/wpcc/base/_all.scss
app/assets/stylesheets/wpcc/base/_section.scss
app/assets/stylesheets/wpcc/base/_wpcc.scss
app/assets/stylesheets/wpcc/section/_all.scss
app/assets/stylesheets/wpcc/section/_details.scss
app/views/layouts/wpcc/engine.html.erb
app/views/wpcc/your_details/new.html.erb

This PR refactors the SASS file structure for readability
Some classnames have also been amended, and markup & JS changed to reflect these changes.
Structure is as follows:
As more development takes place we will no doubt add a components directory and a layout directory, this is a good starting point to guide us in the right direction as we develop further.

[DEV APPROVED] Refactors SASS structure

---

app/assets/stylesheets/wpcc/section/_contributions.scss
app/views/wpcc/your_details/new.html.erb
config/locales/cy.yml
config/locales/en.yml

This PR adds the basic markup, css (including responsive behaviour) and content for English and Welsh

[DEV APPROVED] Adds initial markup, css and content for step 2

---

app/controllers/wpcc/your_details_controller.rb
app/models/wpcc/your_details_form.rb
app/presenters/wpcc/your_details_form_presenter.rb
app/views/wpcc/calculator/_your_contributions.html.erb
app/views/wpcc/your_details/new.html.erb
config/locales/cy.yml
config/locales/en.yml
lib/wpcc/engine.rb
spec/controllers/your_details_controller_spec.rb
spec/models/your_details_form_spec.rb
spec/presenters/your_details_form_presenter_spec.rb

This PR addresses part of [User Story 8389](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8389).
Technical Detail
* Add additional attributes to the your details form model
* Validate the new attributes to only allow specific values
* Add a presenter to remove some logic from the form view
* Amend the controller #new method to use the 'presented' object

[DEV APPROVED] 8389 - Additional Validations for Step 1, Your Details Form

---

Gemfile
Gemfile.lock
app/models/wpcc/contributions_calendar.rb
lib/wpcc/engine.rb

**TP user story**
https://moneyadviceservice.tpondemand.com/entity/8309
**Context**
We are adding rubocop to be added in the build script on GO CI that will be done in the 8290 user story.
We fixed one error on the rubocop to garantee a a code with no rubocop offenses.

8309 add rubocop

---

app/assets/stylesheets/wpcc/application.scss
app/assets/stylesheets/wpcc/base/_wpcc.scss
app/assets/stylesheets/wpcc/components/_all.scss
app/assets/stylesheets/wpcc/components/_tooltip.scss
app/assets/stylesheets/wpcc/section/_contributions.scss
app/assets/stylesheets/wpcc/section/_details.scss
app/views/wpcc/your_details/new.html.erb

This PR brings the Radio selects in step 1 in line with the prototype, also adds some padding to the tooltip.

Adds some minor CSS styles to step 1

---

.gitignore
build.sh
test.sh

This addresses User Story - https://moneyadviceservice.tpondemand.com/entity/8290
Add build and test shell scripts for CI

8290 add wpcc to go ci

---

.gitignore
Gemfile
Gemfile.lock
README.md
spec/rails_helper.rb

PR to add code coverage for all Rspec test

8290 - Add Simplecov

---

app/models/wpcc/salary_frequency_converter.rb
spec/models/salary_frequency_converter_spec.rb

This pr addresses part of [TP User Story](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8285/silent).
The converter will be required for several calculations and views so it made sense to abstract it to its own class.

[DEV APPROVED] Convert salary frequency to a number

---

app/assets/stylesheets/wpcc/section/_results.scss
app/controllers/wpcc/your_contributions_controller.rb
app/controllers/wpcc/your_results_controller.rb
app/views/wpcc/your_results/index.html.erb
config/contribution_periods.yml
config/locales/cy.yml
config/locales/en.yml
features/step_definitions/your_results_steps.rb
features/support/ui/your_results.rb
features/your_details_section.feature
features/your_results.feature
lib/wpcc/version.rb
spec/controllers/your_contributions_controller_spec.rb
spec/controllers/your_results_controller_spec.rb

This pr addresses [Task 8397 of User Story 8286](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=task/8397).

[DEV APPROVED] 8397 step2 amend session v2

---

app/assets/javascripts/wpcc/components/ConditionalMessaging.js
app/views/wpcc/your_details/new.html.erb
config/locales/cy.yml
config/locales/en.yml

Fixes conditional message for male between 65 and 74 and female between 64 and 74.

8209 - Update to conditional messages

---

Gemfile.lock
app/controllers/wpcc/your_details_controller.rb
app/views/wpcc/your_contributions/new.html.erb
app/views/wpcc/your_details/new.html.erb
features/step_definitions/generate_percentages_for_your_contributions_steps.rb
features/step_definitions/your_contributions_steps.rb
features/your_contributions.feature
spec/controllers/your_details_controller_spec.rb

Initial implementation for [User Story 8283](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=74E24C42BB81286E55C11FA8BF7FAAF3#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/8283) to enable the demo to easily navigate between step1 and step2

[]DEV APPROVED] Add ability to edit your details to the your contributions page

---

Gemfile.lock
lib/wpcc/version.rb

Bump version to 1.2

---

app/assets/javascripts/wpcc/BlankTest.js
package.json
spec/javascripts/fixtures/BlankTest.html
spec/javascripts/karma.conf.js
spec/javascripts/test-main.js
spec/javascripts/tests/BlankTest_spec.js
test.sh

This PR adds Karma to the WPCC Repo to facilitate tests to be written for specific components. 
There is a blank test added as part of this work which does nothing but ensures the tests do not fail.

[DEV APPROVED] TP: 8411, Comment: Adds Karma to WPCC

---

app/assets/stylesheets/wpcc/section/_results.scss
app/views/wpcc/your_results/index.html.erb
config/locales/cy.yml
config/locales/en.yml
features/your_details_section.feature

This updates the markup and styles to create the third view of the tool.

[DEV APPROVED] TP: 8207, Comment: Updates markup and styles for 3rd view

---

app/controllers/wpcc/your_details_controller.rb
app/views/wpcc/your_contributions/new.html.erb
app/views/wpcc/your_details/new.html.erb
spec/controllers/your_details_controller_spec.rb

As a conversation in the slack with @margOnline I will share here too:
1) I started the edit step 2 (user story).
2) I follow the same code that was there for the step 1.
3) Then I realise that could be more simple.
4) Then I changed my step 2.
5) Then I finished but notice the difference between the codes.
… 6) Then I thought: “Let me time-box for 15 minutes to do the same with step 1”. The I finished in less than 10 minutes the refactor of the step 1.
7) **I don’t want to conflict with anyone's work but I found another way more simple, to do the same thing. And only I discover now and not before after look more deep on how it is working.**
Obs.: My main purpose was not to conflict with other people's work, I just have an idea on my branch and decided to apply the idea first to another …

Remove your details session fetch & assigned to form object

---

README.md

This pr lists the tasks we need to complete before launching the WPCC tool.

[DEV APPROVED] - Todo checklist

---

Gemfile.lock
app/controllers/wpcc/your_details_controller.rb
app/views/wpcc/your_details/new.html.erb
features/step_definitions/your_contributions_steps.rb
features/step_definitions/your_details_section_steps.rb
features/support/ui/your_contributions.rb
features/support/ui/your_details.rb
features/your_contributions.feature

This pr refactors pr #32 which was rushed through for the initial demo to facilitate navigation between the journey steps.
Add a class method to YourDetailsForm to allow us to loop through its attributes and create instance variables from the session.
Updates the cucumber feature for editing your details from the results page.

[DEV APPROVED] Refactor editing your details

---

HISTORY.md
lib/wpcc/version.rb
test.sh

Bump version to 1.4.0 - all tests passing - incorporates 3 new PR's since last version bump

Bump version

---

app/views/wpcc/your_details/new.html.erb

This PR fixes two cucumber scenarios on master.
Please as a reminder don't forget to run the tests before pushing cc @Tr4pSt3R @willhall88 @margOnline @johnplayer1982 @davidtrussler 
To run just type: `./test.sh` in the project. It is added on the Readme too.

ensure gender gets selected

---

app/assets/javascripts/wpcc/require_config.js.erb
app/views/wpcc/your_details/new.html.erb
config/locales/cy.yml
config/locales/en.yml

This applies the Validation Dough component to the form on the first view. It checks whether the all the fields have values entered and adds an error message if not.

[DEV APPROVED] TP: 8384, Comment: View 1, adds client side validation for form

---

features/calculation_monthly_frequency.feature
spec/models/salary_per_year_spec.rb

This user story is about to calculate monthly figures. More details: https://moneyadviceservice.tpondemand.com/entity/8430
Since the salary per year was implemented on the other branch there is no extra work to be done, just adding cucumber and specs. 
*Obs.: About the cukes possible refactoring to be using datatables is being handle by Will and NOT on this PR*.

8430 calculation monthly

---

app/controllers/wpcc/engine_controller.rb
app/views/wpcc/your_contributions/new.html.erb
features/auto_enrolment_conditional_messaging.feature
features/step_definitions/auto_enrolment_conditional_messaging_steps.rb

Adds Cucumber to Margo's branch for the same story
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/wpcc/65)

Adds conditional messages for auto-enrolment into pension scheme

---

app/views/wpcc/your_contributions/new.html.erb
config/locales/cy.yml
config/locales/en.yml

Adds client-side error messages for the form on Step 2 for: 
- Blank fields
- Out of range values

[DEV APPROVED] - TP: 8438, Comment: Adds client-side validation to Step 2

---

config/locales/cy.yml

This simple PR updates the Welsh content in the 2 callouts for the following tickets:
1) https://moneyadviceservice.tpondemand.com/entity/8436
2) https://moneyadviceservice.tpondemand.com/entity/8437

[DEV APPROVED] - This PR updates 2 conditional messages with Welsh translations

---

app/assets/stylesheets/wpcc/section/_results.scss
app/views/wpcc/your_results/_period_percents_table.html.erb
app/views/wpcc/your_results/index.html.erb
config/locales/cy.yml
config/locales/en.yml

Adds the markup and styles to the percentage table on the results view and adds the component to show and hide this as required.
N.B. This will merge into branch 8434-percent-table and any conflicts and some formatting issues will be resolved at that stage.

8434_percent-table_Frontend

---

.gitignore
Gemfile
features/_your_contributions/your_contributions_calculating_eligible_salary.feature
features/_your_contributions/your_contributions_displaying.feature
features/_your_contributions/your_contributions_editing.feature
features/_your_details/your_details_disabling_minimum_contributions.feature
features/_your_details/your_details_displaying.feature
features/_your_details/your_details_editing.feature
features/_your_results/contribution_above_legal_minimum.feature
features/_your_results/your_results_calculating_different_salary_frequencies.feature
features/manually_opt_in_message.feature
features/step_definitions/manually_opt_in_message_steps.rb
features/step_definitions/your_contributions_steps.rb
features/step_definitions/your_details_steps.rb
features/step_definitions/your_results_steps.rb
features/support/ui/your_contributions.rb
features/support/ui/your_results.rb
features/your_results_frequency_selector.feature

[TP 8445](https://moneyadviceservice.tpondemand.com/entity/8445)
This PR will address refactoring of all cucumber tests to follow a standard format that can be readable and understandable for all. Please raise comments/suggestions or concerns if you don't like some of the refactors :)

8445 - Refactor cucumber

---

app/assets/javascripts/wpcc/require_config.js.erb
app/assets/stylesheets/wpcc/base/_section.scss
app/assets/stylesheets/wpcc/print.scss
app/views/layouts/wpcc/engine.html.erb
app/views/wpcc/shared/_your_details.html.erb
app/views/wpcc/your_results/index.html.erb
config/locales/cy.yml
config/locales/en.yml
lib/wpcc/engine.rb

1) Adds a link to the page: 
2) Creates a new stylesheet for a printed version of the page:

[DEV APPROVED] TP: 8214, Comment: Adds "Print your results" link to Step 3

---

features/step_definitions/your_contributions_steps.rb

Fixes the expectation of a cucumber step now that the markup has changed accordingly

Fix broken cucumber step

---

app/presenters/wpcc/message_presenter.rb
app/views/wpcc/shared/_your_details.html.erb
app/views/wpcc/your_details/new.html.erb
config/locales/cy.yml
config/locales/en.yml
features/_your_details/your_details_displaying.feature
features/step_definitions/your_details_steps.rb
spec/presenters/message_presenter_spec.rb

This pr addresses [TP User Story 8469](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=ddd7f3a626844ab8d1bee3f06ec28efa#page=userstory/8250&searchPopup=UserStory/8469).
On Steps 2 and 3, format the summary of Your Details to make more readable.
Use a presenter method to interpolate the keys for the translations.

[DEV APPROVED] - 8469 Step 1 enhancements

---

README.md
hooks/pre-push

One thing that is happening with some frequency is: some PRs are being merged with the master with some tests failing or other exceptions being raised when app starts. 
So running tests every time there is a push it is my proposed solution.
I am adding a script that will be executed *every time someone push their code* and the instructions on the Readme as well.
**Please, do not review until lightning talk tomorrow.**

[DEV APPROVED] Add git pre push hook

---

HISTORY.md
lib/wpcc/version.rb

This is related to the fix translation missing here #97.

Bump version from 1.5.0 to 1.5.1

---

app/controllers/wpcc/your_contributions_controller.rb
app/presenters/wpcc/period_contribution_presenter.rb
app/presenters/wpcc/presenter.rb
app/presenters/wpcc/your_contribution_presenter.rb
app/views/wpcc/your_contributions/new.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/presenters/presenter_spec.rb
spec/presenters/your_contribution_presenter_spec.rb

This pr formats values displayed in Step 2 to make them more readable.
* Move number to currency formatting to the parent presenter class.
* New presenter specifically for contributions.
* Amend translations to use variables for dynamic values.
* Remove unused translation
* Use the already defined constants for the Upper and Lower Earnings thresholds.

[DEV APPROVED] Format currency amounts

---

lib/wpcc/version.rb

Bump it per recommendation from @willhall88 as there's been a lot changes to the WPCC tool since the last version bump.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/wpcc/123)

[DEV APPROVED] Bumps from v1.6.0 to v1.7.0

---

app/assets/stylesheets/wpcc/base/_wpcc.scss
app/assets/stylesheets/wpcc/components/_all.scss
app/assets/stylesheets/wpcc/components/_global-alert.scss
app/views/layouts/wpcc/engine.html.erb
app/views/wpcc/shared/_beta_warning.html.erb
config/locales/cy.yml
config/locales/en.yml
lib/wpcc/version.rb

[Ticket 8532](https://moneyadviceservice.tpondemand.com/entity/8532)
| Desktop |
|----------|
|![image](https://user-images.githubusercontent.com/13165846/29911971-eddc6c98-8e27-11e7-811b-4a625d19a633.png)|
| Mobile |
|--------|
|<img src="https://user-images.githubusercontent.com/13165846/29911983-fcc306ea-8e27-11e7-86c8-8c91bf11e3fd.png" width="400" />|

[DEV APPROVED] 8532 - BETA warning

---

HISTORY.md
README.md
app/views/layouts/wpcc/engine.html.erb
config/locales/cy.yml
config/locales/en.yml
lib/wpcc.rb
lib/wpcc/version.rb
wpcc.gemspec

[TP Ticket 8568](https://moneyadviceservice.tpondemand.com/entity/8568)
This PR adds SEO content to the WPCC tool.
**In Summary**
- Adds meta-tags dependency
- Adds page title for English and Welsh
- Adds meta description for English and Welsh
- Adds canonical URL for English and Welsh

[DEV APPROVED] 8568 - WPCC SEO Requirements

---

HISTORY.md
lib/wpcc/version.rb
test.sh

Not mission critical in any way. just reducing excess noise output on test script. 
Personal preference. if people don't like it say so and just close this PR :)

[DEV APPROVED] Set test script to run quietly - less noise

---

Dockerfile
HISTORY.md
Jenkinsfile
lib/wpcc/version.rb
script/build

amending the build process to package and upload gems to gem server using Jenkins/Docker,
wpcc v 1.11.5 has already been built and uploaded to gem server

[DEV APPROVED] Add build step to jenkins

---

config/locales/cy.yml
config/locales/en.yml

TP Ticket: [TP8611](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8611&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==)
This updates the text in the Beta tag to change the use of the term "problems" to the softer "feedback" (English and Welsh). 
**Before:**
**After**

[DEV APPROVED] TP: 8611, Comment: Updates text in Beta tag

---

config/locales/cy.yml
config/locales/en.yml
lib/wpcc/version.rb

Ticket: [TP8619](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8619)
This updates the age-related conditional message on Step 1 to remove some content that sometimes contradicts the conditional message relating to the salary field. 
**Current:**
**Updated:**

[DEV APPROVED] TP: 8619, Comment: Updates age-related conditional messaging

---

HISTORY.md

Apologies I forgot to add an update to the history file for this PR:
https://github.com/moneyadviceservice/wpcc/pull/172

Adds updated entry to history.md

---

app/presenters/wpcc/message_presenter.rb
app/views/wpcc/shared/_your_details.html.erb
features/manually_opt_in_message.feature

This is a copy of #179, but to merge into this feature branch and not master.

Fix bad tests + ensure below limit message shows for non-JS

---

lib/wpcc/version.rb

Some of the changes don't appear to have come through with the published gem. bumping a patch to force those changes through.

bump version from 1.13.0 to 1.13.1

---

HISTORY.md
lib/wpcc/version.rb

[TP link](https://moneyadviceservice.tpondemand.com/entity/8446-wpcc-store-app-specific-settings)
This PR bumps the version for the work done on PR #186

Bump to 1.14.0

---

Dockerfile
Jenkinsfile
script/build
script/test

**Adding the Build stage**
Introducing the build stage into Jenkins WPCC pipeline. It should only run the build stage when on master branch.
**Update Ubuntu version**
- The Jenkins Docker image utilised Ubuntu 17.04, which has become end of life. This PR rolls back the version to 16.04 LTS (Long Term Support).
**Move to RVM**
- Previously we were compiling ruby from source, however we have come across number of errors when older version of Ruby require additional patches to be installed. Therefore I implemented RVM (Ruby Version Manager) to manage the installation and patches.
**Security Testing**
- I have also updated the test script to run Brakeman tests for informational purposes. The Jenkins job will not fail if errors and/or warnings occur, but the report will be available in the …

[DEV APPROVED] Add build stage into Jenkins pipeline & additional improvements

---

config/locales/cy.yml
config/locales/en.yml

[TP 8907](https://moneyadviceservice.tpondemand.com/entity/8907-wpcc-remove-reference-to-2018-increases)
Removes reference to increase in minimum contribution rates in 2018.

[DEV APPROVED] - 8907: Remove reference to 2018 rate increase

---

app/presenters/wpcc/message_presenter.rb
config/contribution_calculations.yml
config/locales/cy.yml
config/locales/en.yml
features/_your_contributions/percent_validation.feature
features/_your_results/contribution_above_legal_minimum.feature
spec/models/minimum_contribution_calculator_spec.rb
spec/presenters/message_presenter_spec.rb

[TP Card](https://moneyadviceservice.tpondemand.com/entity/8904-wpcc-update-default-contributions-to-201819)
This PR updates the legal minimum contributions percentages for employees and employers.
~**N.B.** It's currently branched off https://github.com/moneyadviceservice/wpcc/pull/195, which has yet to be squashed (I will do that once it has been reviewed).~ That's now done.

[DEV APPROVED] 8904 update default auto enrolment contribution levels

---

config/locales/cy.yml
config/locales/en.yml

[TP Card](https://moneyadviceservice.tpondemand.com/entity/10278-nty-wpcc-remove-title-text-that)
- Due to changes in the New Tax Year, there is no
need to display this additional information

[DEV APPROVED] 10278 - Remove references to possible increases

---

config/locales/cy.yml
config/locales/en.yml
lib/wpcc/version.rb

[TP 10508](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10508/silent)
Update error messages in accordance with the Welsh translation request.

10508 Update error messages on step 2

---

config/locales/cy.yml
config/locales/en.yml

[TP12081](https://maps.tpondemand.com/entity/12081-wpcc-update-all-links)
This PR updates the next steps links found in the last page of the tool.

12081 - Update Next Steps Links
